
name: 'fake deploy to AWS S3'
description: 'v 119 in section 9'
inputs:
  foo:
    description: input string
    required: true 
outputs:
  bar:
    description: result string
runs:
  using: 'node16'
  main: 'main.js'
