
name: misc

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: run misc script
        run: ./misc.sh
