name: my-env
on:
  push:
    branches:
      - main
env:
  MONGODB_DB_NAME: my-gha-demo
jobs:
  my-sanity-check:
    environment: uat
    env:
      MY_FOO_BAR: foobar5150
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MY_FOO: ${{ secrets.MY_FOO }} 
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Output information
        run: |
          # default
          echo "TRACER actor: $GITHUB_ACTOR"
          echo "TRACER repo: $GITHUB_REPOSITORY"
          echo "TRACER workflow: $GITHUB_WORKFLOW"
          echo "TRACER job: $GITHUB_JOB"
          # workflow
          echo "TRACER db: ${{ env.MONGODB_DB_NAME }}"
          # job
          echo "TRACER MY_FOO_BAR: ${{ env.MY_FOO_BAR }}"
          # secret
          echo "TRACER username: ${{ env.MONGODB_USERNAME }}"
          # uat environment
          echo "TRACER MY_FOO [uat]: ${{ env.MY_FOO }}"

