
name: proj1_push

on: [push]

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: install
        run: npm ci
        working-directory: project1 

      - name: lint
        run: npm run lint
        working-directory: project1 

      - name: test
        run: npm run test
        working-directory: project1 

      - name: build
        run: npm run build
        working-directory: project1 

