name: project9_section9
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: 'true'
          working-dir: './project9'
      - name: Lint code
        run: npm run lint
        working-directory: ./project9
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: load & cache dependencies
        id: loadcache
        uses: ./.github/actions/cached-deps
        with:
          caching: 'true'
          working-dir: './project9'
      - name: action output sanity check
        run: |
          echo "TRACER 24-NOV output cache: ${{ steps.loadcache.outputs.used-cache }}"
          echo "TRACER 24-NOV output date-time: ${{ steps.loadcache.outputs.date-time }}"
      - name: Test code
        id: run-tests
        run: npm run test
        working-directory: ./project9
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./project9/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: 'true'
          working-dir: './project9'
      - name: Build website
        run: npm run build
        working-directory: ./project9
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ./project9/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
  information:
    runs-on: ubuntu-latest
    steps:
      -name: run custom JS action
       uses: ./.github/actions/deploy-s3-javascript

