        # run: echo "TRACER bar result: ${{ needs.client.outputs.result-code }}"

name: section7_bar
on:
  push:
    branches:
      - main
jobs:
  client:
    uses: ./.github/workflows/s7_foo.yml 
    with:
      param1: '5150'

  result-for-foo:
    needs: client
    runs-on: ubuntu-latest
    steps:
      - name: show result of foo
        run: echo "TRACER wth?"
        # run: echo "TRACER bar result: XXX" 
