name: section7_bar
on:
  push:
    branches:
      - main
jobs:
  client-for-foo:
    uses: ./.github/workflows/s7_foo.yml 
    with:
      param1: '5150'
  result-for-foo:
    needs: client-for-foo
    runs-on: ubuntu-latest
    steps:
      - name: show result of foo
      - run: echo "TRACER [bar] result: ${{ needs.client-for-foo.outputs.result-code }}"

