name: section7_matrix
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 17]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }} 
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} 
      - name: Install dependencies
        run: npm install
        working-directory: project6
      - name: Build
        run: npm run build
        working-directory: project6
